### ISSUE TITLE
HTTPS calls

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [Subito-it/SBTUITestTunnel#31] opened 2017-05-20 19:08 UTC
Does SBTUITest support https calls, when I try to monitor HTTPS calls that have custom headers the request fails, does SBTUITest need to support SSL certificates like Charles proxy?https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/

**Comment by tcamin** [comment] 2017-05-20 19:20
We're successfully using the tunnel to monitor ssl requests, so I would say it should work. Can you provide an example of these requests, so that I can take a look? If Charles is open during the test, have you tried closing it?

**Comment by Ashraf-Ali-aa** [comment] 2017-05-20 19:30
@tcamin after looking at the logs, HTTPS calls does work but I got a feeling the issue may be due to https://github.com/Subito-it/SBTUITestTunnel/issues/29 since the mocking data fails to load when trying to mock URLs that require custom headers/tokens.

**Comment by tcamin** [comment] 2017-05-20 19:33
I fear the problem is #29, gonna close this.

**Closed by tcamin** 2017-05-20 19:33 UTC
