### ISSUE TITLE
The GCDWebServer 4.0.0 release broke our builds

### ISSUE THREAD

**Issue by richieshilton** [Subito-it/SBTUITestTunnel#176] opened 2023-06-09 06:25 UTC
Since the update of GCDWebServer 4.0.0  overnight, our builds are failing with the following errors:

	Use of undeclared identifier 'GCDWebServerURLEncodedFormRequest'
	Expected expression
	Use of undeclared identifier 'GCDWebServerURLEncodedFormRequest'
	Use of undeclared identifier 'GCDWebServerURLEncodedFormRequest'
	Unknown type name 'GCDWebServerDataResponse'; did you mean 'GCDWebServerResponse'?
	Unknown receiver 'GCDWebServerDataResponse'; did you mean 'GCDWebServerResponse'?
	No known class method for selector 'responseWithJSONObject:'
	Testing cancelled because the build failed.

We're currently importing SBTUITestTunnel  through SPM, pinning to commit `1c9b846f95ff683d66c732f8a6fe6d604f50ec16` for fixes on master that weren’t part of a release, however we have the same issue if we update to the latest release, or the latest version.

**Comment by djs-code** [comment] 2023-06-09 14:31
Still broken for us as well; our CI is effectively at a standstill.  

@tcamin It looks like the GCDWebServer fork needs a public signing key?

![Screen Shot 2023-06-09 at 10 25 22 AM](https://github.com/Subito-it/SBTUITestTunnel/assets/11869755/12da216d-0bd0-4e43-b9d1-41b182c33dd8)

**Comment by tcamin** [comment] 2023-06-09 15:22
Can you adding the tunnel package and pinning to the `hotfix/spm` branch?

**Comment by djs-code** [comment] 2023-06-09 15:45
@tcamin Confirmed that the hotfix branch did the trick.  Can we expect this to be merged in shortly?

**Comment by tcamin** [comment] 2023-06-09 16:08
Merged

**Closed by tcamin** 2023-06-09 16:08 UTC
